name: Generate Site

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean site --file pom.xml
    - name: Deploy Site
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: target/site
        ssh-key: ${{ secrets.DEPLOY_KEY }}